### ISSUE TITLE
Mqtt Error

### ISSUE THREAD

**Issue by DenioD** [danielfett/inetbox.py#27]
Hey,

i have a problem to get States to my MQTT Broker. Connection is fine but i get on startup:  

```
2022-12-05 18:06:25,229  truma.main  WARNING    Service configuration for truma not found in 'services' section of configuration file /etc/miqro.yml. Using empty configuration.
2022-12-05 18:06:25,229  truma.main  INFO       started
2022-12-05 18:06:25,229  truma.main  INFO       Opening serial device /dev/serial0 in exclusive mode
2022-12-05 18:06:25,232  truma.main  INFO       Loop stats:
2022-12-05 18:06:25,232  truma.main  INFO        - Loop(_update_online_status) called 0 times, average duration 0.0s, load=0%
2022-12-05 18:06:25,232  truma.main  INFO        - Loop(send_status) called 0 times, average duration 0.0s, load=0%
2022-12-05 18:06:25,233  truma.main  INFO        - Loop(commit_updates) called 0 times, average duration 0.0s, load=0%
2022-12-05 18:06:25,233  truma.main  INFO        - Loop(send_update_status) called 0 times, average duration 0.0s, load=0%
2022-12-05 18:06:25,233  truma.main  INFO        - Loop(send_cp_plus_status) called 0 times, average duration 0.0s, load=0%
2022-12-05 18:06:25,243  truma.main  INFO       MQTT connected, client=<paho.mqtt.client.Client object at 0x7fb21b7d00>, userdata=None, rc=0
2022-12-05 18:06:25,244  truma.main  INFO       Subscribing to ...
2022-12-05 18:06:25,244  truma.main  INFO         - service/truma/set/#
2022-12-05 18:06:25,244  truma.main  INFO         - service/truma/enabled
2022-12-05 18:06:25,360  inet.protocol  INFO    Responding to 08 message (updates_to_send={})!
2022-12-05 18:06:25,422  inet.protocol  INFO    Received read by identifier request.
2022-12-05 18:06:25,456  truma.mqtt  ERROR      Caught exception in on_message: _on_enable() takes 2 positional arguments but 3 were given
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/home/pi/.local/lib/python3.9/site-packages/miqro/__init__.py", line 421, in _on_message
    handler(self, payload)
TypeError: _on_enable() takes 2 positional arguments but 3 were given
2022-12-05 18:06:25,778  inet.protocol  INFO    Responding to 08 message (updates_to_send={})!
2022-12-05 18:06:25,841  inet.protocol  INFO    Received read by identifier request.
2022-12-05 18:06:26,197  inet.protocol  INFO    Responding to 08 message (updates_to_send={})!
2022-12-05 18:06:26,259  inet.protocol  INFO    Received read by identifier request.
2022-12-05 18:06:26,615  inet.protocol  INFO    Responding to 08 message (updates_to_send={})!
2022-12-05 18:06:26,678  inet.protocol  INFO    Received read by identifier request.
2022-12-05 18:06:27,034  inet.protocol  INFO    Responding to 08 message (updates_to_send={})!
2022-12-05 18:06:27,097  inet.protocol  INFO    Received read by identifier request.```

Running System is Raspbian 64 Bit. Heater: Truma Combi 4 - Panel is Inet Ready.

Does anyone had this problem and could help me to fix it? 

Thanks!

**Comment by pkoevesdi** [comment]
I have the same problem and ask myself: why is this closed? I see,  @AndreasL384 opened a duplicate #35 of this, so I'm obviously not the only person who consideres this not to be closed. I'll take a try to fix this.
